//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int QuestionOptionID { get; set; }
        public Nullable<int> Numeric { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Bool { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
    
        public virtual QuestionOptions QuestionOptions { get; set; }
        public virtual UnitOfMeasures UnitOfMeasures { get; set; }
        public virtual Answers Answers1 { get; set; }
        public virtual Answers Answer1 { get; set; }
        public virtual User User { get; set; }
    }
}
