//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doque.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answers> Answers { get; set; }
        public DbSet<InputTypes> InputTypes { get; set; }
        public DbSet<OptionChoices> OptionChoices { get; set; }
        public DbSet<OptionGroups> OptionGroups { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<QuestionOptions> QuestionOptions { get; set; }
        public DbSet<Questions> Questions { get; set; }
        public DbSet<SurveyComments> SurveyComments { get; set; }
        public DbSet<SurveyHeader> SurveyHeader { get; set; }
        public DbSet<SurveySection> SurveySection { get; set; }
        public DbSet<UnitOfMeasures> UnitOfMeasures { get; set; }
        public DbSet<UserSurveySections> UserSurveySections { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
