//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionChoices
    {
        public OptionChoices()
        {
            this.QuestionOptions = new HashSet<QuestionOptions>();
        }
    
        public int ID { get; set; }
        public int OptionGroupID { get; set; }
        public string Name { get; set; }
    
        public virtual OptionGroups OptionGroups { get; set; }
        public virtual ICollection<QuestionOptions> QuestionOptions { get; set; }
    }
}
