//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.QuestionOptions = new HashSet<QuestionOptions>();
        }
    
        public int ID { get; set; }
        public int SurveySectionID { get; set; }
        public int InputTypeID { get; set; }
        public string Name { get; set; }
        public string Subtext { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<int> OptionGroupID { get; set; }
        public Nullable<bool> AllowMultipleOptionAnsers { get; set; }
    
        public virtual InputTypes InputTypes { get; set; }
        public virtual OptionGroups OptionGroups { get; set; }
        public virtual ICollection<QuestionOptions> QuestionOptions { get; set; }
        public virtual SurveySection SurveySection { get; set; }
    }
}
