//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyHeader
    {
        public SurveyHeader()
        {
            this.SurveyComments = new HashSet<SurveyComments>();
            this.SurveySection = new HashSet<SurveySection>();
        }
    
        public int ID { get; set; }
        public int OrganizationID { get; set; }
        public string SurveyName { get; set; }
        public string Instructions { get; set; }
        public string OtherHeaderInfo { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<SurveyComments> SurveyComments { get; set; }
        public virtual ICollection<SurveySection> SurveySection { get; set; }
    }
}
