//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answers = new HashSet<Answers>();
            this.SurveyComments = new HashSet<SurveyComments>();
            this.UserSurveySections = new HashSet<UserSurveySections>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<System.DateTime> Invite { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> InviterUserID { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<SurveyComments> SurveyComments { get; set; }
        public virtual ICollection<UserSurveySections> UserSurveySections { get; set; }
    }
}
